### ISSUE TITLE
Language selector throw

### ISSUE THREAD

**Issue by dtopuzov** [Sitefinity/nextjs-renderer#32]
Steps to reproduce:
1. npm run dev
2. open the admin portal and add new Language Selector widget
3. the following error is thrown on dev server console:
```
 ⨯ TypeError: Cannot read properties of undefined (reading 'Site')
    at LanguageSelector (./src/components/language-selector/language-selector.tsx:19:39)
    at stringify (<anonymous>)
 ⨯ TypeError: Cannot read properties of undefined (reading 'Site')
    at LanguageSelector (./src/components/language-selector/language-selector.tsx:19:39)
    at stringify (<anonymous>)
digest: "3630649938"
```

**Comment by dtopuzov** [comment]
The component test for this widget (see tests/language-selector.test.tsx) fails too:
```
    TypeError: Cannot read properties of undefined (reading 'Site')

       9 |     console.log(JSON.stringify(props, null, 3));
      10 |     const context = props.requestContext;
    > 11 |     const cultures = context.pageNode.Site.Cultures;
         |                                       ^
      12 |     let values: PageItem[] = [];
      13 |
      14 |     if (context.pageNode != null) {

      at Site (src/components/language-selector/language-selector.tsx:11:39)
      at Object.<anonymous> (tests/language-selector.test.tsx:55:49)
```
